### ISSUE TITLE
Reliance on registry for Windows 10 detection breaks use under Mono

### ISSUE THREAD

**Issue by 20kdc** [usagirei/RGSS-Decryptor#1]
Under Mono (commonly used under Linux), access to the registry redirects to a fake registry, which unfortunately requires root permissions to get at (for some bizzare reason).
The Windows 10 check unfortunately breaks things before the program can even start, because of the registry access.
(A possible workaround might be to consider throwing an exception during registry access as a 'no'.)
I don't know if there are further issues past this, cannot test at present.
Right now it's possible to use the released version of the decryptor under Wine, as thankfully it is not compiled for a 'too high' .NET version.

(This specifically occurred on version v1.0.0.0, but the relevant source code still exists, so I believe it is safe to assume this still occurs.)

**Comment by usagirei** [comment]
I've pushed a new version, along with a compiled binary, which assume Unix/MacOSX Terminals to be ANSI compilant (which they should, therefore being able to use escape codes natively), and fallback to registry check only on Windows Platforms.

**Comment by 20kdc** [comment]
The issue is fixed. Testing now shows that the use of '\\' instead of '/' causes issues, but the program is at least usable now so long as the user has a way to clean that up. Thanks!
(Windows-style forward-slash-option-format forbids absolute directory paths, many files created with '\\' in their name rather than the intended directories & files)
